name: TMCS
main: me.playajames.tmcs.Main
version: 0.5
author: playajames
database: true

commands:
  tmcs:
    description: The Minecraft Server main command.
  database:
    description: Database core control command.
  db:
    description: Alias of database command.
  test:
    description: Test command for development purposes.
  money:
    desctiption: Display's amount of money player has.
  warp:
    desctiption: Warp control command.
  warps:
    desctiption: Warp control command.
  spawn:
    desctiption: Teleports player to spawn location.
  clan:
    desctiption: Clan control command.
  clans:
    desctiption: Clan control command.